### ISSUE TITLE
Containerize Dogehouse

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [benawad/dogehouse#101]
## About the Problem

Installing dependencies for the backend (Elxir API / Voice/WSS server) and frontend (React webapp / Puppeteer shenanigans AKA UI Tests and Lighthouse checks) is a mess and may cause dependency hell if left unmanged, and running them one-by-one can be also an distater.

## Solution and To-Dos

* [x] Make an `docker-compose.yml` file in the root directory that includes each subdirectiry's Dockerfiles required for running the instance + database backend.
* [x] Create an `Dockerfile` on each folder in the Dogehouse monorepo.

**Comment by AndreiJirohHaliliDev2006** [comment]
For scaling, use Kubernetes, but the problem is Docker support in Kubernetes will be removed by version 1.22. So, this may requires making own Helm charts without Docker.

**Comment by Salman2301** [comment]
So Far this is my docker-compose

- [ ] need to run DB migrations?
- [ ] need to communicate with voice server

```
version: "3"
services:
  database:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRE_DB=postgres
  voice_server:
    build: ./shawarma
    depends_on: 
      - backend

  backend:
    build: ./kousa
    depends_on: 
      - database
    environment: 
      - DATABASE_URL=ecto://postgres:postgres@127.0.0.1/postgres
      - BEN_GITHUB_ID={username}
      - RABBITMQ_URL=amqp://192.168.1.165:3000 # Not sure about this
      - SENTRY_DNS=NO_IDEA_WHAT_THIS_IS
      - GITHUB_CLIENT_ID=5d5xxxxxxab70
      - GITHUB_CLIENT_SECRET=48xxxxxxxxxxxxd1cd5
      - ACCESS_TOKEN_SECRET=8f51exxxxxx7211dd
      - REFRESH_TOKEN_SECRET=dbb85xxxxxx9ebde
    networks:
      - frontend
    ports:
      - 4001:4001

  frontend:
    build: ./kofta
    networks: 
      - db
    ports:
      - 3000:3000

networks:
  db:
  frontend:
  ```

**Comment by AndreiJirohHaliliDev2006** [comment]
> So Far this is my docker-compose
> 
> * [ ]  need to run DB migrations?
> * [ ]  need to communicate with voice server
> 
> ```
> version: "3"
> services:
>   database:
>     image: postgres
>     environment: 
>       - POSTGRES_USER=postgres
>       - POSTGRES_PASSWORD=postgres
>       - POSTGRE_DB=postgres
>   voice_server:
>     build: ./shawarma
>     depends_on: 
>       - backend
> 
>   backend:
>     build: ./kousa
>     depends_on: 
>       - database
>     environment: 
>       - DATABASE_URL=ecto://postgres:postgres@127.0.0.1/postgres
>       - BEN_GITHUB_ID={username}
>       - RABBITMQ_URL=amqp://192.168.1.165:3000 # Not sure about this
>       - SENTRY_DNS=NO_IDEA_WHAT_THIS_IS
>       - GITHUB_CLIENT_ID=5d5xxxxxxab70
>       - GITHUB_CLIENT_SECRET=48xxxxxxxxxxxxd1cd5
>       - ACCESS_TOKEN_SECRET=8f51exxxxxx7211dd
>       - REFRESH_TOKEN_SECRET=dbb85xxxxxx9ebde
>     networks:
>       - frontend
>     ports:
>       - 4001:4001
> 
>   frontend:
>     build: ./kofta
>     networks: 
>       - db
>     ports:
>       - 3000:3000
> 
> networks:
>   db:
>   frontend:
> ```

@Salman2301 It's not needed to expose the port for the PostgresDB server port. The only thing we need to expose is the frontend UI and the backend API/voice server. Also, we need volumes for the database to ensure no data is lost after shutting down the server.

Speaking of the DB migrations, because there's no documentation yet, I may look over the codebase later. As for communicating with the voice server, yes, we need to have an way to communicate with the websocket server.

**Comment by AndreiJirohHaliliDev2006** [comment]
As both the backend API and the websocket server has its own Dockerfiles, and since the frontend is deployed through Netlify, we don't need the Dockerfile for the frontend. @Salman2301

**Comment by Salman2301** [comment]
I just keep Dockerfile for frontend 
so, we can start and stop all the containers during local dev.

I think there is some DB migrations stuff in `kousa/priv/repo/migrations/*.exs`
That we run in Dockerfile for kousa

IDK what's the SentryDNS 
do we needed for local environments?

**Comment by ianjaku** [comment]
> IDK what's the SentryDNS
> do we needed for local environments?

This seems to be a typo, should be DSN ([Data Source Name](https://docs.sentry.io/product/sentry-basics/dsn-explainer/)).
Basically tells sentry where to send your events.

It's used in releases.exs so it doesn't get used in development and you can probably just remove it from the docker-compose environment variables.

**Comment by Salman2301** [comment]
@ianjaku  If i remove it, it throws the error 
Cause the Dockerfile in kousa set the env as a production and we can create a new docker file for developement
to avoid it may be?

**Comment by ianjaku** [comment]
Could be interesting to also add add adminer to the docker-compose file, It's extremely light weight and can be useful for testing.

Would be:

```
  adminer:
    image: adminer
    restart: "no"
    ports:
      - 5051:8080
    depends_on:
      - database
```

Data for postgres is located at /var/lib/postgresql/data so to add a volume we would need to add:

```
# In the database section
volumes:
  - dbdata:/var/lib/postgresql/data
      
# At the bottom of the file
volumes:
  dbdata:
```
